### ISSUE TITLE
Use huawei custom api for Image Management

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-incubator/bosh-huaweicloud-cpi-release#30]
The huawei cpi currently uses the [openstack glance API](https://developer.openstack.org/api-ref/image/) for image management. This issue is to clarify whether the cpi would use huawei [custom api for Image Management](https://support.huaweicloud.com/en-us/api-ims/en-us_topic_0020091562.html)

**Comment by zhongjun2** [comment]
We have no plan to implement the custom api for Image Management to provide differentiated features now.
