### ISSUE TITLE
Use huawei ECS api for instance management

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-incubator/bosh-huaweicloud-cpi-release#31]
The huawei cpi currently uses the [openstack compute API](https://developer.openstack.org/api-ref/compute/index.html ) for instance management. This issue is to clarify whether the cpi would use huawei [custom ESC API](https://support.huaweicloud.com/en-us/api-ecs/en-us_topic_0020212657.html) in the future to provide differentiated features

**Comment by zhongjun2** [comment]
We will use our own HuaweiCloud API in huaweicloud CPI in the future.
